// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjMlK0ULoSdZbQBTqLVZJS451s7xuZvA0',
    appId: '1:356176493140:web:37ae0a2d5e1cab67818bc1',
    messagingSenderId: '356176493140',
    projectId: 'stock-management-tool-876b9',
    authDomain: 'stock-management-tool-876b9.firebaseapp.com',
    storageBucket: 'stock-management-tool-876b9.appspot.com',
    measurementId: 'G-M3598CNZ4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNoFmsc5nH6XhpxR66DkyX6kMvpYUkNo',
    appId: '1:356176493140:android:15d2eb75a376525c818bc1',
    messagingSenderId: '356176493140',
    projectId: 'stock-management-tool-876b9',
    storageBucket: 'stock-management-tool-876b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPmWMsOv_vMrraZv_Th3eTIAmSlqoih8',
    appId: '1:356176493140:ios:f46052d752e6962d818bc1',
    messagingSenderId: '356176493140',
    projectId: 'stock-management-tool-876b9',
    storageBucket: 'stock-management-tool-876b9.appspot.com',
    iosBundleId: 'com.nanosoft.stockManagementTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiPmWMsOv_vMrraZv_Th3eTIAmSlqoih8',
    appId: '1:356176493140:ios:e54e7ca5d12ed47c818bc1',
    messagingSenderId: '356176493140',
    projectId: 'stock-management-tool-876b9',
    storageBucket: 'stock-management-tool-876b9.appspot.com',
    iosBundleId: 'com.nanosoft.stockManagementTool.RunnerTests',
  );
}
